### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by amir-ippon** [ibm-cloud-architecture/refarch-eda#131]
Hi there,

https://github.com/ibm-cloud-architecture/refarch-eda-store-simulator repository that is referenced in a couple of labs including https://ibm-cloud-architecture.github.io/refarch-eda/scenarios/realtime-inventory/ and https://ibm-cloud-architecture.github.io/refarch-eda/use-cases/connect-rabbitmq/ seems to have been moved elsewhere.

**Comment by jesusmah** [comment]
Hi @amir-ippon, thanks for opening this issue. I have reviewed 

https://ibm-cloud-architecture.github.io/refarch-eda/scenarios/realtime-inventory/ and found a dead link that I fixed through https://github.com/ibm-cloud-architecture/refarch-eda/pull/132

However, https://github.com/ibm-cloud-architecture/refarch-eda-store-simulator does not seem like a dead link as it opens up fine for me. I have also reviewed https://ibm-cloud-architecture.github.io/refarch-eda/use-cases/connect-rabbitmq/ and could not find a dead link, they all opened up for me too.

**Comment by amir-ippon** [comment]
Hi @jesusmah, That is very weird because when I try and open https://github.com/ibm-cloud-architecture/refarch-eda-store-simulator I get a 404! could it be a permission issue of some sort assuming that repo is meant to be public!? Thank you.

**Comment by jbcodeforce** [comment]
Hi yes it was private. I just changed the visibility so now it should be visible.

**Comment by amir-ippon** [comment]
@jbcodeforce Thank you!
