### ISSUE TITLE
Add to the guide how to run mkdocs via a docker image

### ISSUE THREAD

**Issue by jborup** [ibm-cloud-architecture/refarch-eda#15]
Suggest to add this section to the README.md

#### Building this booklet locally but with docker
In some cases you might not want to alter your Python setup and rather go with a docker image instead. This requires docker is running locally on your computer though.

1. docker pull squidfunk/mkdocs-material
2. `git clone https://github.com/ibm-cloud-architecture/refarch-eda.git` _(or your forked repository if you plan to edit)_
3. docker run --rm -it -p 8000:8000 -v ${PWD}:/docs squidfunk/mkdocs-material
4. Go to `http://127.0.0.1:8000/` in your browser.

Source: [mkdcocs with Material in docker](https://squidfunk.github.io/mkdocs-material/getting-started/#alternative-using-docker)

**Comment by jbcodeforce** [comment]
integrated
