### ISSUE TITLE
Align EDA project repositories under github.com/ibm-cloud-architecture

### ISSUE THREAD

**Issue by osowski** [ibm-cloud-architecture/refarch-eda#37]
Align all the repositories under https://github.com/ibm-cloud-architecture that are critical to the EDA reference architecture. 

The high-level entry-point repository should remain as `refarch-eda`.
The low-level implementation repository is currently `refarch-kc` (with **kc** being short for **kcontainer** - as it is a reference implementation for shipping containers.

All other component repositories (either high or low-level) are being proposed to be of the format `refarch-eda-XYZ` or `refarch-kc-XYZ`.

Repositories of note that we need to evaluate:
- https://github.com/ibm-cloud-architecture/refarch-reefer-ml

**Comment by jbcodeforce** [comment]
naming convention for project

eda-ZYZ
refarch-kc-ZYZ
eda-quickstarts is for the code template
eda-gitops-catalog is for the operator catalog
eda-XYZ-gitops is for a specific solution gitops

All repo should have eda tag so we easily find them on eda keyword searsh
