### ISSUE TITLE
Broken link for Kafka on Kubernetes using stateful sets

### ISSUE THREAD

**Issue by josiemundi** [ibm-cloud-architecture/refarch-eda#58]
In the following doc:
https://github.com/ibm-cloud-architecture/refarch-eda/edit/master/docs/src/pages/additional-reading/index.mdx

The link for Kafka on Kubernetes using stateful sets leads to 'Page not found': 
https://github.com/kubernetes/contrib/tree/master/statefulsets/Kafka

**Comment by jbcodeforce** [comment]
I removed it

**Comment by osowski** [comment]
Closing per https://github.com/ibm-cloud-architecture/refarch-eda/issues/58#issuecomment-632353354
