### ISSUE TITLE
Broken link: Our skill journey 

### ISSUE THREAD

**Issue by josiemundi** [ibm-cloud-architecture/refarch-eda#59]
In the doc:

https://github.com/ibm-cloud-architecture/refarch-eda/blob/master/docs/src/pages/additional-reading/index.mdx

The following link for 'Our skill journey' is broken:
https://github.com/ibm-cloud-architecture/refarch-eda/blob/master/docs/src/pages/additional-reading/training/eda-skill-journey.md

**Comment by josiemundi** [comment]
The following link is also broken on the same 'additional reading' page:

https://github.com/ibm-cloud-architecture/refarch-integration/tree/master/docs/serverless

**Comment by jbcodeforce** [comment]
removed this section too as we have new content on serverless somewhere else and we have to od a deep study to do serverless with kafka anyway
